server:
    port: 8008
spring: 
  application:
    name: ms-inventory-t3b
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      failFast: true
      #name of base properties config file, before profile
#      name: config-client
      #profile: development
      #label: latest
#      username: admin
#      password: qwerty
#      retry: 
#        max-attempts: 1     
#        max-interval: 1000
eureka:  
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true