server:
    port: 8090
spring:
  application:
    name: ms-gateway-t3b
  cloud:
    gateway:
      routes:
      - id: ms-oauth-t3b
        uri: lb://ms-oauth-t3b
        predicates:
          - Path=/oauth/**
      - id: ms-picking-t3b
        uri: lb://ms-picking-t3b
        predicates:
          - Path=/PickingMS/Global/picking/**
      - id: ms-rutas-t3b
        uri: lb://ms-rutas-t3b
        predicates:
          - Path=/WEBT3BRutas2021/**
      - id: ms-usuarios-t3b
        uri: lb://ms-usuarios-t3b
        predicates:
          - Path=/Usuarios/**
      - id: ms-inventory-t3b
        uri: lb://ms-inventory-t3b
        predicates:
          - Path=/inventory/**
  security:
    user:
      name: sergey
      password: sergey    
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  file:
    name: gateway .log