server:
    port: 8090
spring:
  application:
    name: ms-gateway-t3b
  cloud:
    gateway:
      routes:
      - id: ms-oauth-t3b
        uri: lb://ms-oauth-t3b
        predicates:
          - Path=/oauth/**
      - id: ms-picking-t3b
        uri: lb://ms-picking-t3b
        predicates:
          - Path=/PickingMS/Global/picking/**
      - id: ms-rutas-t3b
        uri: lb://ms-rutas-t3b
        predicates:
          - Path=/WEBT3BRutas2021/**
      - id: ms-usuarios-t3b
        uri: lb://ms-usuarios-t3b
        predicates:
          - Path=/Usuarios/**
      - id: ms-inventory-t3b
        uri: lb://ms-inventory-t3b
        predicates:
          - Path=/inventory/**
      - id: ms-customer-t3b
        uri: lb://ms-customer-t3b
        predicates:
          - Path=/customer/**
      - id: ms-catalogos-almacen
        uri: lb://ms-catalogos-almacen
        predicates:
          - Path=/almacen/rest/sync/**
      - id: ms-epackage-t3b
        uri: lb://ms-epackage-t3b
        predicates:
          - Path=/almacen/rest/epackage/**
          
                
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      
management: 
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
config:
  security:
    oauth:
      jwt:
        key: 9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp3
        
logging:
  file:
    path: /opt/logs/
    name: ${logging.file.path}gateway.log
  pattern:
    console: 