server:
  port: 8087
    
spring: 
  application:
    name: ms-usuarios-t3b
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    
management: 
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
logging:
  pattern:
    console: 
    
springdoc:
  swagger-ui:
    path: /Usuarios/docs/swagger
  api-docs:
    path: /Usuarios/docs/api-docs
      
